zeebe:
  client:
    cloud:
      clientId: myspringapp
      clientSecret: Nz48wd8rUmE0CxR1QOjLtW3VSABrmp2a
      authUrl: http://localhost:18080/auth/realms/camunda-platform/protocol/openid-connect/token
    broker:
      grpcAddress: http://localhost:26500
      restAddress: http://localhost:8080
    security:
      plaintext: true
